#!/usr/bin/env python3
"""
Show ALL position sizing multipliers and where they can be configured
"""

def show_all_multipliers():
    print("=" * 80)
    print("🎯 ALL POSITION SIZING MULTIPLIERS IN ZWESTA TRADING SYSTEM")
    print("=" * 80)
    print()
    
    print("📊 FINAL POSITION SIZE CALCULATION:")
    print()
    print("   position_size = basePositionSize")
    print("                   × quality_multiplier      (1.0-1.2x)")
    print("                   × symbol_multiplier       (0.7-10x)")
    print("                   × consecutive_loss_mult   (0.75x if 2+ losses)")
    print("                   × session_performance     (0.7x if struggling)")
    print("                   × equity_curve_mult       (up to 1.5x if profitable)")
    print()
    print("   → CAPPED at 12.0x maximum (allows 1.2 × 10 = 12x)")
    print("   → FLOORED at 0.5x minimum (protects from going too small)")
    print()
    
    print("=" * 80)
    print("1️⃣ BASE POSITION SIZE")
    print("=" * 80)
    print()
    print("   📍 Location: Bot configuration database field")
    print("   📊 Default: 0.01 lots")
    print("   🔧 How to change:")
    print("      - Use _increase_position_size.py script")
    print("      - Or update via API/database directly")
    print()
    print("   💰 Impact:")
    print("      0.01 = Conservative baseline")
    print("      0.02 = 2x more aggressive (double position)")
    print("      0.05 = 5x more aggressive")
    print("      0.10 = 10x more aggressive (very risky!)")
    print()
    print("   ⚠️ Recommended: 0.01-0.02 for accounts under R2,000")
    print()
    
    print("=" * 80)
    print("2️⃣ QUALITY MULTIPLIER (Signal Strength)")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~3255 in multi_broker_backend_updated.py")
    print("   📊 Values:")
    print("      - 1.2x if score >= 9.0 AND RR >= 2.5 (EXCELLENT setup)")
    print("      - 1.0x otherwise (normal setup)")
    print()
    print("   🔧 How to change:")
    print("      size_multiplier = 1.2 if score >= 9.0 and rr_value >= 2.5 else 1.0")
    print()
    print("      Could increase to:")
    print("      - 1.5x for excellent setups (score >= 9.0)")
    print("      - 1.3x for very good setups (score >= 8.0)")
    print("      - 1.0x for normal setups")
    print()
    print("   💡 Example modification:")
    print("      size_multiplier = (")
    print("          1.5 if score >= 9.0 and rr_value >= 2.5")
    print("          else 1.3 if score >= 8.0")
    print("          else 1.0")
    print("      )")
    print()
    
    print("=" * 80)
    print("3️⃣ SYMBOL PERFORMANCE MULTIPLIER ⭐ (JUST UPGRADED TO 10X)")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~24382 - SYMBOL_PERF_FAVOR_MULT constant")
    print("   📊 Current Value: 10.0 (changed from 1.5)")
    print()
    print("   🎯 Verdict System:")
    print("      - 'favored': 10.0x multiplier (net profit > 0, WR > 60%)")
    print("      - 'normal': 1.0x multiplier (default)")
    print("      - 'demoted': 0.5x multiplier (WR < 45%)")
    print("      - 'blacklisted': 0.0x (blocked from trading)")
    print()
    print("   📊 Calculation Logic (Line ~24631):")
    print("      if net_pnl > SYMBOL_PERF_FAVOR_PROFIT and win_rate > SYMBOL_PERF_FAVOR_WINRATE:")
    print("          verdict = 'favored'")
    print("          multiplier = SYMBOL_PERF_FAVOR_MULT  # 10.0x!")
    print("      elif net_pnl <= SYMBOL_PERF_BLACKLIST_LOSS or win_rate < SYMBOL_PERF_BLACKLIST_WINRATE:")
    print("          verdict = 'blacklisted'")
    print("          multiplier = 0.0")
    print("      elif win_rate < SYMBOL_PERF_DEMOTE_WINRATE:")
    print("          verdict = 'demoted'")
    print("          multiplier = SYMBOL_PERF_DEMOTE_MULT  # 0.5x")
    print("      else:")
    print("          verdict = 'normal'")
    print("          multiplier = 1.0")
    print()
    print("   🔧 How to change:")
    print("      Edit SYMBOL_PERF_FAVOR_MULT constant:")
    print("      - Current: 10.0 (aggressive)")
    print("      - Conservative: 3.0-5.0")
    print("      - Moderate: 6.0-8.0")
    print("      - Aggressive: 10.0-15.0")
    print("      - Insane: 20.0+ (not recommended!)")
    print()
    print("   💡 For clients: Keep at 1.5-3.0 for safety")
    print()
    
    print("=" * 80)
    print("4️⃣ CONSECUTIVE LOSS PENALTY")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~3260")
    print("   📊 Values:")
    print("      - 0.75x if consecutiveLosses >= 2")
    print("      - 1.0x otherwise (no penalty)")
    print()
    print("   🔧 How to change:")
    print("      if int(bot_config.get('consecutiveLosses') or 0) >= 2:")
    print("          size_multiplier *= 0.75  # Could change to 0.5 or 0.9")
    print()
    print("   💡 Purpose: Reduces risk after losing streaks")
    print()
    print("   🎯 Possible improvements:")
    print("      - After 2 losses: 0.9x (gentle reduction)")
    print("      - After 3 losses: 0.75x (moderate reduction)")
    print("      - After 5 losses: 0.5x (aggressive reduction)")
    print("      - After 7 losses: 0.25x (pause near-pause)")
    print()
    
    print("=" * 80)
    print("5️⃣ SESSION PERFORMANCE MULTIPLIER")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~23372")
    print("   📊 Values:")
    print("      - 0.7x if recent performance is poor")
    print("      - 1.0x otherwise")
    print()
    print("   🔧 Constants (Line ~24432):")
    print("      SESSION_PERF_DEMOTE_MULT = 0.7")
    print("      SESSION_PERF_DEMOTE_WINRATE = 0.45")
    print()
    print("   💡 Purpose: Reduces size during struggling periods")
    print()
    
    print("=" * 80)
    print("6️⃣ EQUITY CURVE MULTIPLIER (Account Growth)")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~18369")
    print("   📊 Values:")
    print("      equity_multiplier = 1.0 + (total_profit / 1000)")
    print("      Capped at 1.5x maximum")
    print()
    print("   💰 Examples:")
    print("      +$100 profit  → 1.10x multiplier")
    print("      +$500 profit  → 1.50x multiplier (capped)")
    print("      +$1000 profit → 1.50x multiplier (capped)")
    print()
    print("   🔧 How to change:")
    print("      equity_multiplier = 1.0 + (total_profit / 500)  # Faster scaling")
    print("      size *= min(equity_multiplier, 2.0)  # Higher cap")
    print()
    print("   💡 Purpose: Grow position size as account profits")
    print()
    
    print("=" * 80)
    print("7️⃣ OVERALL SIZE CAP")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~3262")
    print("   📊 Current: min(size_multiplier, 12.0)")
    print()
    print("   🔧 How to change:")
    print("      size_multiplier = round(max(0.5, min(size_multiplier, 12.0)), 3)")
    print("                                              ^^^^ Change this")
    print()
    print("   💰 Examples:")
    print("      - 12.0 = Current (allows 1.2 quality × 10 symbol)")
    print("      - 15.0 = Higher (allows more scaling)")
    print("      - 20.0 = Very high (risky!)")
    print("      - 6.0  = Conservative (safer for clients)")
    print()
    print("   ⚠️ WARNING: Higher cap = higher risk!")
    print()
    
    print("=" * 80)
    print("8️⃣ VOLATILITY-BASED SIZING (Per Symbol)")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~16411+ (SYMBOL_VOLATILITY_CONFIGS)")
    print("   📊 ATR Multipliers per symbol:")
    print()
    print("   Forex:")
    print("      EURUSD: atr_multiplier = 1.2")
    print("      GBPUSD: atr_multiplier = 1.3  (more volatile)")
    print("      USDJPY: atr_multiplier = 1.2")
    print()
    print("   Crypto:")
    print("      BTCUSDT: atr_multiplier = 1.8")
    print("      ETHUSDT: atr_multiplier = 2.0  (very volatile)")
    print()
    print("   Commodities:")
    print("      XAUUSD (Gold): atr_multiplier = 2.0")
    print("      USOIL: atr_multiplier = 2.0")
    print()
    print("   🔧 How to change:")
    print("      Edit the dictionary entries:")
    print("      'GBPUSD': {'atr_multiplier': 1.5, ...}  # Increase")
    print()
    print("   💡 Purpose: Adjusts stop-loss distances, not position size")
    print()
    
    print("=" * 80)
    print("9️⃣ PROFIT PROTECTION (Position Lock-In)")
    print("=" * 80)
    print()
    print("   📍 Location: Line ~29157 (DEFAULT_PROFIT_PROTECTION_CONFIG)")
    print("   📊 Default Values:")
    print("      retainProfitPct: 0.50 (lock in 50% of profit)")
    print("      trailingStopPct: 0.30 (30% trailing stop)")
    print("      minProfitToArm: 0.30 (arm at 30% profit)")
    print()
    print("   🔧 How to change in bot config:")
    print("      bot_config['profitProtection'] = {")
    print("          'enabled': True,")
    print("          'retainProfitPct': 0.70,  # Lock 70% of profit")
    print("          'trailingStopPct': 0.20,  # Tighter trailing")
    print("          'minProfitToArm': 0.20    # Arm earlier")
    print("      }")
    print()
    print("   💡 Purpose: Protects profits once target is reached")
    print()
    
    print("=" * 80)
    print("🎯 PRACTICAL EXAMPLES")
    print("=" * 80)
    print()
    
    print("EXAMPLE 1: Conservative Setup (Current)")
    print("-" * 80)
    print("   Base: 0.01 lots")
    print("   Quality: 1.0x (normal setup)")
    print("   Symbol: 1.0x (GBPUSDm not yet 'favored')")
    print("   Consecutive: 1.0x (no losses)")
    print("   Session: 1.0x (normal performance)")
    print("   Equity: 1.0x (no profit yet)")
    print("   → FINAL: 0.01 × 1.0 × 1.0 × 1.0 × 1.0 × 1.0 = 0.01 lots")
    print()
    
    print("EXAMPLE 2: GBPUSDm After Becoming 'Favored'")
    print("-" * 80)
    print("   Base: 0.01 lots")
    print("   Quality: 1.2x (excellent setup, score=9.5)")
    print("   Symbol: 10.0x (GBPUSDm 'favored' verdict!)")
    print("   Consecutive: 1.0x (no losses)")
    print("   Session: 1.0x (normal performance)")
    print("   Equity: 1.0x (no profit yet)")
    print("   → CALCULATION: 0.01 × 1.2 × 10.0 = 0.12 lots")
    print("   → FINAL: 0.12 lots (12x more than baseline!) ✅")
    print()
    
    print("EXAMPLE 3: Maximum Possible (All Bonuses)")
    print("-" * 80)
    print("   Base: 0.02 lots (doubled)")
    print("   Quality: 1.2x (excellent setup)")
    print("   Symbol: 10.0x (favored)")
    print("   Consecutive: 1.0x (no losses)")
    print("   Session: 1.0x (good performance)")
    print("   Equity: 1.0x")
    print("   → CALCULATION: 0.02 × 1.2 × 10.0 = 0.24 lots")
    print("   → But if base was 0.10:")
    print("      0.10 × 1.2 × 10.0 = 1.2 lots (CAPPED AT 12x)")
    print()
    
    print("EXAMPLE 4: After 2 Losses (Penalty Applied)")
    print("-" * 80)
    print("   Base: 0.01 lots")
    print("   Quality: 1.0x")
    print("   Symbol: 10.0x (still favored)")
    print("   Consecutive: 0.75x (2 losses penalty!)")
    print("   → CALCULATION: 0.01 × 1.0 × 10.0 × 0.75 = 0.075 lots")
    print("   → FINAL: 0.075 lots (25% reduction due to losses)")
    print()
    
    print("=" * 80)
    print("🔧 RECOMMENDED MODIFICATIONS FOR YOUR SETUP")
    print("=" * 80)
    print()
    
    print("FOR PERSONAL TRADING (R1,375 account):")
    print("   ✅ Keep basePositionSize = 0.01")
    print("   ✅ Keep SYMBOL_PERF_FAVOR_MULT = 10.0")
    print("   ✅ Keep quality multiplier = 1.2")
    print("   ✅ Keep overall cap = 12.0")
    print("   → Result: Up to 0.12 lots on favored GBPUSDm")
    print()
    
    print("FOR CLIENT ACCOUNTS ($100-500):")
    print("   🛡️ Set basePositionSize = 0.01")
    print("   🛡️ REDUCE SYMBOL_PERF_FAVOR_MULT to 3.0 (safer)")
    print("   🛡️ Keep quality multiplier = 1.2")
    print("   🛡️ REDUCE overall cap to 6.0")
    print("   → Result: Max 0.036 lots (3.6x, much safer)")
    print()
    
    print("FOR AGGRESSIVE TRADING (R5,000+ account):")
    print("   🚀 Increase basePositionSize to 0.03")
    print("   🚀 Increase quality excellent bonus to 1.5x")
    print("   🚀 Keep SYMBOL_PERF_FAVOR_MULT = 10.0")
    print("   🚀 Increase overall cap to 20.0")
    print("   → Result: Max 0.45 lots (45x, very aggressive!)")
    print()
    
    print("=" * 80)
    print("📋 STEP-BY-STEP: HOW TO MODIFY MULTIPLIERS")
    print("=" * 80)
    print()
    
    print("1. CHANGE SYMBOL PERFORMANCE MULTIPLIER:")
    print("   File: C:\\backend\\multi_broker_backend_updated.py")
    print("   Line: ~24382")
    print("   Find: SYMBOL_PERF_FAVOR_MULT = 10.0")
    print("   Change to: SYMBOL_PERF_FAVOR_MULT = 5.0  # Or your value")
    print()
    
    print("2. CHANGE QUALITY MULTIPLIER:")
    print("   File: C:\\backend\\multi_broker_backend_updated.py")
    print("   Line: ~3255")
    print("   Find: size_multiplier = 1.2 if score >= 9.0 and rr_value >= 2.5 else 1.0")
    print("   Change to: size_multiplier = 1.5 if score >= 9.0 and rr_value >= 2.5 else 1.0")
    print()
    
    print("3. CHANGE OVERALL CAP:")
    print("   File: C:\\backend\\multi_broker_backend_updated.py")
    print("   Line: ~3262")
    print("   Find: size_multiplier = round(max(0.5, min(size_multiplier, 12.0)), 3)")
    print("   Change to: size_multiplier = round(max(0.5, min(size_multiplier, 6.0)), 3)")
    print()
    
    print("4. CHANGE CONSECUTIVE LOSS PENALTY:")
    print("   File: C:\\backend\\multi_broker_backend_updated.py")
    print("   Line: ~3260")
    print("   Find: size_multiplier *= 0.75")
    print("   Change to: size_multiplier *= 0.5  # Harsher penalty")
    print()
    
    print("5. CHANGE BASE POSITION SIZE:")
    print("   Run: python _increase_position_size.py")
    print("   Edit new_size variable to desired value")
    print()
    
    print("6. RESTART BACKEND:")
    print("   cd C:\\backend")
    print("   python -B multi_broker_backend_updated.py")
    print()
    
    print("=" * 80)
    print("⚠️ CRITICAL REMINDERS")
    print("=" * 80)
    print()
    print("   1. ALL multipliers stack (multiply together)")
    print("   2. 10x symbol multiplier = 10x DRAWDOWN too!")
    print("   3. Test changes with small basePositionSize first")
    print("   4. Monitor first 20 trades after any change")
    print("   5. Have max daily loss limits in place")
    print("   6. Different settings for clients vs personal trading")
    print()
    print("=" * 80)

if __name__ == "__main__":
    show_all_multipliers()
